name: Server Test

on:
  push:
    branches:
      - master

jobs:
  integration-test:
    name: Integration Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: "3.9"

      - uses: robinraju/release-downloader@v1.7
        name: Download Sample Data
        with:
          tag: "misc"
          fileName: "*"

      - name: Unzip Sample Data
        run: |
          mkdir service/data
          unzip data.zip -d service/data
          rm data.zip

      - name: Move Checkpoints
        run: |
          mkdir service/checkpoints
          mv audio_model_trill.pt service/checkpoints
          mv linguistic_head_en.ckpt service/checkpoints
          mv linguistic_head_zh.ckpt service/checkpoints

      - name: Install Dependencies
        working-directory: ./service
        run: |
          sudo apt update
          sudo apt install -y ffmpeg
          pip install "pip<24.1"
          pip install tensorflow==2.9.1
          pip install torch==1.11.0+cpu torchvision==0.12.0+cpu torchaudio==0.11.0 --extra-index-url https://download.pytorch.org/whl/cpu
          pip install numpy==1.26.4 numba==0.60.0 pyzmq==24.0.1 scipy==1.13.1 tensorneko==0.2.7 transformers==4.24.0 hsemotion==0.3 facenet_pytorch==2.5.2 tensorflow_hub==0.12.0 pydub==0.25.1 librosa==0.9.2 BeautifulSoup4==4.11.1 moviepy==1.0.3 lxml==4.9.1 pandas==1.3.5 fastapi==0.89.0 starlette==0.22.0 uvicorn==0.20.0 websockets==10.4 python-multipart==0.0.5 timm==0.9.7 torchmetrics==0.11.4
          pip install openai_whisper==20231117

      - name: Run Test for ZH
        working-directory: ./service
        run: python test/integration_test.py --video_path ./data/1/video.mp4 --lang zh
        env:
          PYTHONPATH: ${{ github.workspace }}/service

      - name: Run Test for EN
        working-directory: ./service
        run: python test/integration_test.py --video_path ./data/1/video.mp4 --lang en
        env:
          PYTHONPATH: ${{ github.workspace }}/service
